import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MAGZ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="bg-blue-500">
          Tailwind is working
        </h1>

        <h1 className="bg-purple-600">
           Hi my name is Marie 
        </h1>

        <h2 className="bg-orange-600">
          Snippet
          https://res.cloudinary.com/dyun86hau/image/upload/v1669911018/IMG20220212155940_kmvzzc.jpg
        </h2>
       

       <img
        src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Cat_November_2010-1a.jpg/220px-Cat_November_2010-1a.jpg"
        alt="spiderman"
      />
      </main>
      
    </div>
  )
}
